{{- $me := .Values.components.monitoring.k8sMonitoring }}
{{- if include "common.managed" $me }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: {{ $me.namespace }}
  annotations:
    {{- if $me.helmResourcePolicyKeep }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  {{- if or
           (include "common.used" .Values.components.monitoring.loki)
           (include "common.used" .Values.components.security.kyverno)
  }}
  dependsOn:
    {{- if include "common.used" .Values.components.monitoring.loki }}
    - name: loki
      namespace: {{ .Values.components.monitoring.loki.namespace }}
    {{- end }}
    {{- if include "common.used" .Values.components.security.kyverno }}
    - name: kyverno
      namespace: {{ .Values.components.security.kyverno.namespace }}
    {{- end }}
  {{- end }}
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: {{ $me.chartName }}
      version: {{ $me.chartVersion | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ $me.chartRepository | quote }}
        namespace: {{ $.Release.Namespace }}
      interval: 1h
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    {{- include "monitoring.k8sMonitoring.mergedValues" . | nindent 4 }}
{{- end }}
