{{- $me := .Values.components.monitoring.thanos }}
{{- if include "common.managed" $me }}
{{- if ne .Values.components.monitoring.kubePrometheusStack.namespace $me.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $me.namespace }}
  annotations:
    {{- if $me.helmResourcePolicyKeep }}
    helm.sh/resource-policy: keep
    {{- end }}
{{- end }}
{{- end }}
