{{- $me := .Values.components.monitoring.k8sMonitoring }}
{{- if include "common.managed" $me }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $me.namespace }}
  annotations:
    {{- if $me.helmResourcePolicyKeep }}
    helm.sh/resource-policy: keep
    {{- end }}
{{- end }}
