name: Lint and Test Charts

on:
  pull_request:

jobs:
  lint-test:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        test:
        - "test-01-minimal-loki-promtail"
        - "test-02-minimal-loki-k8smonitoring"
        - "test-03-nginx-cert-manager"
        - "test-04-cnpg-x509-certificate-exporter-falco"
        - "test-05-kyverno"
        runson:
        - ubuntu-24.04
        - ubuntu-24.04-arm

    runs-on: [ "${{ matrix.runson }}" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Setup Flux CLI
        if: steps.list-changed.outputs.changed == 'true'
        uses: fluxcd/flux2/action@main

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.13.0

      - name: Install Flux in Kubernetes Kind
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          flux install
          kubectl -n flux-system patch deploy/helm-controller --type=json -p='[{"op":"replace", "path":"/spec/template/spec/containers/0/args/2", "value":"--log-level=debug"}]'
          kubectl rollout status -n flux-system deploy/helm-controller

#      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
#        run: ct install --target-branch ${{ github.event.repository.default_branch }} --skip-clean-up

      - name: Helm install in Kubernetes Kind
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl get events -A -w &
          kubectl -n flux-system logs -f deploy/helm-controller &
          if ! helm install --rollback-on-failure --debug helm-chart-of-the-death charts/helm-chart-of-the-death -f tests/${{ matrix.test }}/values.yaml; then
            kubectl get pods -A
            #kubectl -n infra-nginx-ingress get all
            kubectl -n infra-loki logs loki-0
            exit 1
          fi
          kill %1 %2

#      - name: check installation
#        if: steps.list-changed.outputs.changed == 'true'
#        run: |
#          for i in $(seq 1 60); do
#            date
#            kubectl get pod,helmrelease,ns,secret,events -A
#            kubectl -n flux-system logs deploy/helm-controller
#            helm list -A
#            sleep 3
#          done


